var a=1;
/*while(a<=10){
    console.log(a +"<br>")
    a+=1
}*/
//For loop
/*for(let b=1;b<=10;b++)
{
    console.log( b+ ") Yahoo Baba");
}*/

/* for(let k=1;k<=100;k++){
    if(k==3)
    {
        console.log("Number is:"+k);
        continue;
    }
    
    else{
    console.log("The number is "+ k);
    }
}*/
/*for (let m=1;m<=10;m++)
{
    if(m==5)
    {
        break;
    }
    else{
        console.log("Hello India");
    }
}*/
